### ISSUE TITLE
'struct camera_config_t' has no member named 'fb_location'

### ISSUE THREAD

**Issue by Terbinm** [easytarget/esp32-cam-webserver#269]
I can't pass the compile the code with error:
'struct camera_config_t' has no member named 'fb_location'

**Comment by d3viant** [comment]
The same error here. Arduino 1.8.19 on Windows 11 Intel Thinkpad, AI Thinker Board. Simply edited ssid and pass and saved myconfig.h, got same error.

**Comment by d3viant** [comment]
Solved by upgrading to Arduino IDE 2.0.

**Comment by Semmu** [comment]
I came across the same issue. Unfortunately upgrading Arduino IDE to 2.0 did not solve the issue.

<img width="1392" alt="image" src="https://user-images.githubusercontent.com/1938602/197801229-5777aa8d-8949-4e8d-bb86-a0d3f4a776b0.png">

Strangely enough, the same codebase can be compiled with the PlatformIO command line tools, so I guess this is some configuration issue.

**Comment by Muplex** [comment]
Same error here
Arduino IDE 2.0.1
ESP32 Arduino board 1.0.6

**Comment by Muplex** [comment]
I try in another PC 
fresh installation windows, arduino IDE and so on... same resoult

`C:\Users\nicol\OneDrive\Documenti\Arduino\Esperimenti e Progetti\esp32-cam-webserver\esp32-cam-webserver.ino: In function 'void StartCamera()':
C:\Users\nicol\OneDrive\Documenti\Arduino\Esperimenti e Progetti\esp32-cam-webserver\esp32-cam-webserver.ino:341:12: error: 'struct camera_config_t' has no member named 'fb_location'
     config.fb_location = CAMERA_FB_IN_PSRAM;
            ^
C:\Users\nicol\OneDrive\Documenti\Arduino\Esperimenti e Progetti\esp32-cam-webserver\esp32-cam-webserver.ino:341:26: error: 'CAMERA_FB_IN_PSRAM' was not declared in this scope
     config.fb_location = CAMERA_FB_IN_PSRAM;
                          ^
C:\Users\nicol\OneDrive\Documenti\Arduino\Esperimenti e Progetti\esp32-cam-webserver\esp32-cam-webserver.ino:343:12: error: 'struct camera_config_t' has no member named 'grab_mode'
     config.grab_mode = CAMERA_GRAB_LATEST;
            ^
C:\Users\nicol\OneDrive\Documenti\Arduino\Esperimenti e Progetti\esp32-cam-webserver\esp32-cam-webserver.ino:343:24: error: 'CAMERA_GRAB_LATEST' was not declared in this scope
     config.grab_mode = CAMERA_GRAB_LATEST;
                        ^
Multiple libraries were found for "WiFi.h"
  Used: C:\Users\nicol\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.6\libraries\WiFi
  Not used: C:\Users\nicol\OneDrive\Documenti\Arduino\libraries\WiFiEspAT
Multiple libraries were found for "ArduinoOTA.h"
  Used: C:\Users\nicol\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.6\libraries\ArduinoOTA
  Not used: C:\Users\nicol\OneDrive\Documenti\Arduino\libraries\ArduinoOTA
exit status 1

Compilation error: 'struct camera_config_t' has no member named 'fb_location'`

**Comment by sonofcy** [comment]
IIRC, that is the error you get with the old sketch using the latest esp32 core. The fix was to revert the core back to 1.0.6 but I think the latest version of the sketch does not have that error.

**Comment by Muplex** [comment]
Where I can find sketch lastest version?

**Comment by Muplex** [comment]
> IIRC, that is the error you get with the old sketch using the latest esp32 core. The fix was to revert the core back to 1.0.6 but I think the latest version of the sketch does not have that error.


Where we can find sketch lastest version?

**Comment by sonofcy** [comment]
Ver 4 is at https://github.com/easytarget/esp32-cam-webserver

**Comment by sonofcy** [comment]
ESP32 boards should be 2.0.5 for Ver 4.

**Comment by Muplex** [comment]
> ESP32 boards should be 2.0.5 for Ver 4.

I thin kyou mean 1.0.5 esp32 boards (lastest is 1.0.6)

I try right now to downgrade Esp32 board to 1.0.5 but same resoult same error same lines  :(

any ideas?

**Comment by sonofcy** [comment]
I just downloaded the zip again. Rename zio from esp32-cam-webserver-master to esp32-cam-webserver. Now unzip and compile the ino file BUT set errors to default as ALL will fail on some minor errors. I just did it on IDE 1.

**Comment by sonofcy** [comment]
NO, latest which is 2.0.5

**Comment by Muplex** [comment]
![img](https://user-images.githubusercontent.com/25262524/202858997-90655162-9163-4cc8-8f90-8ef77f81f046.png)

Sorry i'm missing something.

additional board URL is corect ?


`http://arduino.esp8266.com/stable/package_esp8266com_index.json,https://dl.espressif.com/dl/package_esp32_index.json`

**Comment by sonofcy** [comment]
Not even close, here is mine. If you are not working with PICO then leave off the last one

https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json
https://arduino.esp8266.com/stable/package_esp8266com_index.json
https://github.com/earlephilhower/arduino-pico/releases/download/global/package_rp2040_index.json

**Comment by Muplex** [comment]
Thank you I solved, the problem was the additional board URL's 
=)

**Comment by sonofcy** [comment]
> I can't pass the compile the code with error: 'struct camera_config_t' has no member named 'fb_location'

Have you solved your problem?

**Comment by JeanPoll** [comment]
Hmm same issue here, URS are fine, don't know how to fix.

**Comment by briodan** [comment]
running into the same issue

![image](https://github.com/easytarget/esp32-cam-webserver/assets/41130293/159edacd-362e-46ee-a0a7-d132d5ee1fc0)

additional board URL's

http://arduino.esp8266.com/stable/package_esp8266com_index.json,
https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json

installed version
![image](https://github.com/easytarget/esp32-cam-webserver/assets/41130293/5c42ff75-1f8f-4212-8032-97bf078fadc7)

any clue on what else to try?

**Comment by briodan** [comment]
on a whim i tried the windows store version of the arduino ide which installed a different version

![image](https://github.com/easytarget/esp32-cam-webserver/assets/41130293/8ce4494c-43b5-45ef-a827-171e7f2d7529)

which compiled correctly, so i guess an older/different version is what was needed for me,
All else is the same.

**Comment by easytarget** [comment]
Some good info here; I'm also not closing this yet since I want to capture this as I archive the project
